"""admin_revamp_new_entities

Revision ID: daaaab5b4732
Revises: 9b2c_content_ops
Create Date: 2026-08-29 06:13:23.386349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'daaaab5b4732'
down_revision: Union[str, None] = '9b2c_content_ops'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_is_active'), 'brands', ['is_active'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('campaigns',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('banner_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('discount_type', postgresql.ENUM('percentage', 'fixed', name='discounttype', create_type=False), nullable=True),
    sa.Column('discount_value', sa.DECIMAL(precision=14, scale=0), nullable=False),
    sa.Column('max_discount_amount', sa.DECIMAL(precision=14, scale=0), nullable=True),
    sa.Column('applies_to_all', sa.Boolean(), nullable=False),
    sa.Column('category_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_is_active'), 'campaigns', ['is_active'], unique=False)
    op.create_index(op.f('ix_campaigns_slug'), 'campaigns', ['slug'], unique=True)
    op.create_table('contact_messages',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_is_read'), 'contact_messages', ['is_read'], unique=False)
    op.create_table('faq_items',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_items_category'), 'faq_items', ['category'], unique=False)
    op.create_index(op.f('ix_faq_items_is_active'), 'faq_items', ['is_active'], unique=False)
    op.create_index('ix_faq_sort', 'faq_items', ['sort_order'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('login', 'register', 'reset', name='otppurpose', native_enum=False), nullable=True),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_destination'), 'otp_codes', ['destination'], unique=False)
    op.create_index('ix_otp_destination', 'otp_codes', ['destination'], unique=False)
    op.create_table('shipping_methods',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=14, scale=0), nullable=False),
    sa.Column('free_over_amount', sa.DECIMAL(precision=14, scale=0), nullable=True),
    sa.Column('estimated_days_min', sa.Integer(), nullable=False),
    sa.Column('estimated_days_max', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_methods_code'), 'shipping_methods', ['code'], unique=True)
    op.create_index(op.f('ix_shipping_methods_is_active'), 'shipping_methods', ['is_active'], unique=False)
    op.create_table('static_pages',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_pages_is_published'), 'static_pages', ['is_published'], unique=False)
    op.create_index(op.f('ix_static_pages_slug'), 'static_pages', ['slug'], unique=True)
    op.create_table('product_questions',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('answered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_questions_is_published'), 'product_questions', ['is_published'], unique=False)
    op.create_index(op.f('ix_product_questions_product_id'), 'product_questions', ['product_id'], unique=False)
    op.create_index('ix_questions_product_id', 'product_questions', ['product_id'], unique=False)
    op.create_table('product_reviews',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_buyer', sa.Boolean(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('admin_reply', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'user_id', name='uq_review_user_product')
    )
    op.create_index(op.f('ix_product_reviews_is_approved'), 'product_reviews', ['is_approved'], unique=False)
    op.create_index(op.f('ix_product_reviews_product_id'), 'product_reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_reviews_user_id'), 'product_reviews', ['user_id'], unique=False)
    op.create_index('ix_reviews_approved', 'product_reviews', ['is_approved'], unique=False)
    op.create_index('ix_reviews_product_id', 'product_reviews', ['product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('price_delta', sa.DECIMAL(precision=14, scale=0), nullable=False),
    sa.Column('absolute_price', sa.DECIMAL(precision=14, scale=0), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_is_active'), 'product_variants', ['is_active'], unique=False)
    op.create_index('ix_variants_product_id', 'product_variants', ['product_id'], unique=False)
    op.create_index('uq_variants_product_sku', 'product_variants', ['product_id', 'sku'], unique=True)
    op.create_table('stock_notify_requests',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'contact', name='uq_stock_notify_contact')
    )
    op.create_index('ix_stock_notify_product', 'stock_notify_requests', ['product_id'], unique=False)
    op.create_table('coupon_redemptions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coupon_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=14, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_redemptions_coupon_id'), 'coupon_redemptions', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_user_id'), 'coupon_redemptions', ['user_id'], unique=False)
    op.create_index('ix_redemptions_coupon_id', 'coupon_redemptions', ['coupon_id'], unique=False)
    op.create_index('uq_redemption_coupon_user_order', 'coupon_redemptions', ['coupon_id', 'user_id', 'order_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_index('ix_osh_order_id', 'order_status_history', ['order_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gateway', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('authority', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ref_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('amount_toman', sa.DECIMAL(precision=14, scale=0), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.create_index('ix_txn_authority', 'payment_transactions', ['authority'], unique=False)
    op.create_index('ix_txn_order_id', 'payment_transactions', ['order_id'], unique=False)
    op.create_table('return_requests',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('admin_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refund_amount', sa.DECIMAL(precision=14, scale=0), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_requests_order_id'), 'return_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_return_requests_status'), 'return_requests', ['status'], unique=False)
    op.create_index('ix_returns_order_id', 'return_requests', ['order_id'], unique=False)
    op.create_table('review_feedbacks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['product_reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', name='uq_feedback_user_review')
    )
    op.create_index(op.f('ix_review_feedbacks_review_id'), 'review_feedbacks', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_feedbacks_user_id'), 'review_feedbacks', ['user_id'], unique=False)
    op.alter_column('activity_logs', 'metadata_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_id'), 'activity_logs', ['actor_id'], unique=False)
    op.drop_constraint(op.f('addresses_user_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('article_categories_slug_key'), 'article_categories', type_='unique')
    op.create_index(op.f('ix_article_categories_slug'), 'article_categories', ['slug'], unique=True)
    op.alter_column('articles', 'body',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('articles', 'excerpt',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('articles', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('articles', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('articles_slug_key'), 'articles', type_='unique')
    op.create_index(op.f('ix_articles_is_published'), 'articles', ['is_published'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.alter_column('carousels', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('carousels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('carousels', 'starts_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('carousels', 'ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('coupons', sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('coupons', sa.Column('per_user_limit', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('coupons', sa.Column('max_discount_amount', sa.DECIMAL(precision=14, scale=0), nullable=True))
    op.add_column('coupons', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('coupons', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False, server_default=''))
    op.create_index(op.f('ix_coupons_is_active'), 'coupons', ['is_active'], unique=False)
    op.alter_column('newsletter_subscriptions', 'consent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('newsletter_subscriptions', 'unsubscribed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_newsletter_subscriptions_email'), 'newsletter_subscriptions', ['email'], unique=True)
    op.alter_column('notifications', 'body',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('order_items', sa.Column('variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order_items', sa.Column('variant_name_snapshot', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    op.create_foreign_key(None, 'order_items', 'product_variants', ['variant_id'], ['id'])
    op.add_column('orders', sa.Column('shipping_method_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('shipping_method_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    op.add_column('orders', sa.Column('tracking_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('orders', sa.Column('carrier', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('orders', sa.Column('admin_note', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    op.add_column('orders', sa.Column('campaign_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('campaign_discount_amount', sa.Float(), nullable=False))
    op.create_index(op.f('ix_orders_tracking_code'), 'orders', ['tracking_code'], unique=False)
    op.create_foreign_key(None, 'orders', 'shipping_methods', ['shipping_method_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'campaigns', ['campaign_id'], ['id'])
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', type_='unique')
    op.drop_constraint(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.add_column('products', sa.Column('brand_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', type_='unique')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.add_column('roles', sa.Column('permissions', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False, server_default=''))
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.alter_column('settings', 'value',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('settings', 'value_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.drop_constraint(op.f('uq_wishlist_user_product'), 'wishlist_items', type_='unique')
    op.create_index('uq_wishlist_user_product', 'wishlist_items', ['user_id', 'product_id'], unique=True)
    op.drop_constraint(op.f('wishlist_items_product_id_fkey'), 'wishlist_items', type_='foreignkey')
    op.drop_constraint(op.f('wishlist_items_user_id_fkey'), 'wishlist_items', type_='foreignkey')
    op.create_foreign_key(None, 'wishlist_items', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'wishlist_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist_items', type_='foreignkey')
    op.drop_constraint(None, 'wishlist_items', type_='foreignkey')
    op.create_foreign_key(op.f('wishlist_items_user_id_fkey'), 'wishlist_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('wishlist_items_product_id_fkey'), 'wishlist_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_wishlist_user_product', table_name='wishlist_items')
    op.create_unique_constraint(op.f('uq_wishlist_user_product'), 'wishlist_items', ['user_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.alter_column('settings', 'value_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('settings', 'value',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('roles', 'permissions')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_column('products', 'brand_id')
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_tracking_code'), table_name='orders')
    op.drop_column('orders', 'campaign_discount_amount')
    op.drop_column('orders', 'campaign_id')
    op.drop_column('orders', 'admin_note')
    op.drop_column('orders', 'carrier')
    op.drop_column('orders', 'tracking_code')
    op.drop_column('orders', 'shipping_method_name')
    op.drop_column('orders', 'shipping_method_id')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'variant_name_snapshot')
    op.drop_column('order_items', 'variant_id')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'body',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_newsletter_subscriptions_email'), table_name='newsletter_subscriptions')
    op.alter_column('newsletter_subscriptions', 'unsubscribed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('newsletter_subscriptions', 'consent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_coupons_is_active'), table_name='coupons')
    op.drop_column('coupons', 'description')
    op.drop_column('coupons', 'is_active')
    op.drop_column('coupons', 'max_discount_amount')
    op.drop_column('coupons', 'per_user_limit')
    op.drop_column('coupons', 'starts_at')
    op.alter_column('carousels', 'ends_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('carousels', 'starts_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('carousels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('carousels', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_is_published'), table_name='articles')
    op.create_unique_constraint(op.f('articles_slug_key'), 'articles', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('articles', 'published_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('articles', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('articles', 'excerpt',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('articles', 'body',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_article_categories_slug'), table_name='article_categories')
    op.create_unique_constraint(op.f('article_categories_slug_key'), 'article_categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key(op.f('addresses_user_id_fkey'), 'addresses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_activity_logs_actor_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.alter_column('activity_logs', 'metadata_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_review_feedbacks_user_id'), table_name='review_feedbacks')
    op.drop_index(op.f('ix_review_feedbacks_review_id'), table_name='review_feedbacks')
    op.drop_table('review_feedbacks')
    op.drop_index('ix_returns_order_id', table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_status'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_order_id'), table_name='return_requests')
    op.drop_table('return_requests')
    op.drop_index('ix_txn_order_id', table_name='payment_transactions')
    op.drop_index('ix_txn_authority', table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index('ix_osh_order_id', table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index('uq_redemption_coupon_user_order', table_name='coupon_redemptions')
    op.drop_index('ix_redemptions_coupon_id', table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_user_id'), table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_coupon_id'), table_name='coupon_redemptions')
    op.drop_table('coupon_redemptions')
    op.drop_index('ix_stock_notify_product', table_name='stock_notify_requests')
    op.drop_table('stock_notify_requests')
    op.drop_index('uq_variants_product_sku', table_name='product_variants')
    op.drop_index('ix_variants_product_id', table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_is_active'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('ix_reviews_product_id', table_name='product_reviews')
    op.drop_index('ix_reviews_approved', table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_user_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_product_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_is_approved'), table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_index('ix_questions_product_id', table_name='product_questions')
    op.drop_index(op.f('ix_product_questions_product_id'), table_name='product_questions')
    op.drop_index(op.f('ix_product_questions_is_published'), table_name='product_questions')
    op.drop_table('product_questions')
    op.drop_index(op.f('ix_static_pages_slug'), table_name='static_pages')
    op.drop_index(op.f('ix_static_pages_is_published'), table_name='static_pages')
    op.drop_table('static_pages')
    op.drop_index(op.f('ix_shipping_methods_is_active'), table_name='shipping_methods')
    op.drop_index(op.f('ix_shipping_methods_code'), table_name='shipping_methods')
    op.drop_table('shipping_methods')
    op.drop_index('ix_otp_destination', table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_destination'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index('ix_faq_sort', table_name='faq_items')
    op.drop_index(op.f('ix_faq_items_is_active'), table_name='faq_items')
    op.drop_index(op.f('ix_faq_items_category'), table_name='faq_items')
    op.drop_table('faq_items')
    op.drop_index(op.f('ix_contact_messages_is_read'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_campaigns_slug'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_is_active'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_is_active'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
